# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    이슈가 생성되었습니다.
  prs: |
    pr이 생성되었습니다

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  "Bug":
    include:
      - '\bfix\b'
  "Test":
    include:
      - '\btest\b'
  "Feat":
    include:
      - '\bfeat\b'
  "Docs":
    include:
      - '\bdocs\b'
  "Refactor":
    include:
      - '\brefactor\b'
  "CI":
    include:
      - '\bci\b'
