name: pnpm setup
description: pnpm setup

runs:
  using: composite
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    # - uses: actions/cache@v4
    #   name: Setup pnpm cache
    #   id: pnpm-cache
    #   with:
    #     path: ${{ env.STORE_PATH }}
    #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: log cache
      if: ${{steps.pnpm-cache.outputs.cache-hit != 'true'}}
      run: echo "Cache not found"
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash

    # - name: Check if Playwright browser is cached
    #   uses: actions/cache@v3
    #   id: playwright-cache
    #   with:
    #     path: |
    #       ~/.cache/ms-playwright
    #     key: ${{ runner.os }}-playwright-1.28.0

    # - run: npx playwright install --with-deps
    #   if: steps.playwright-cache.outputs.cache-hit != 'true'
    #   shell: bash

    # - run: npx playwright install-deps
    #   if: steps.playwright-cache.outputs.cache-hit == 'true'
    #   shell: bash
