name: pnpm setup
description: pnpm setup
inputs:
  node-version:
    description: "Node.js version"
    required: true
    default: "20"
runs:
  using: composite
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Check if Playwright browser is cached
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-1.28.0

    - run: npx playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash

    - run: npx playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      shell: bash

    - name: Run CI
      run: pnpm run ci
      shell: bash
