name: deploy Storybook to Chromatic
description: Deploys Storybook to Chromatic

inputs:
  projectToken:
    description: "Chromatic project token"
    required: true
  token:
    description: "GitHub token"
    required: true
  workingDir:
    description: "배포할 디렉토리"
    required: false
    default: "packages/ui"
  storybookBuildDir:
    description: "빌드 결과물이 담긴 폴더경로. workingDir이 먼저 적용되니 주의"
    required: false
    default: "storybook-static"

runs:
  using: "composite"
  steps:
    - name: Deploy to Chromatic
      uses: chromaui/action@latest
      shell: bash
      with:
        projectToken: ${{ inputs.projectToken }}
        token: ${{ inputs.token }}
        workingDir: ${{ inputs.workingDir }}
        storybookBuildDir: ${{ inputs.storybookBuildDir }}
