name: playwright-install

runs:
  using: composite

  steps:
    - name: Get playwright version
      shell: bash
      run: |
        echo "PLAYWRIGHT_VERSION=$(node -e "process.stdout.write(require('playwright/package.json').version)")" >> $GITHUB_OUTPUT
      id: playwright-version

    - name: Cache Playwright Browsers for Playwright's Version
      uses: actions/cache@v4
      with:
        # https://playwright.dev/docs/browsers#managing-browser-binaries
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
      id: cache-playwright-browsers

    - name: Setup Playwright
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
