name: Build & Deploy Docs
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - dev
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: ./.github/actions/setup

      - name: build
        run: pnpm turbo build

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Check changed paths
        id: check-paths
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            if [[ $file == app/docs/* ]]; then
              echo "DOCS_CHANGED=true" >> $GITHUB_ENV
            fi
            if [[ $file == packages/ui/* ]]; then
              echo "UI_CHANGED=true" >> $GITHUB_ENV
            fi
          done

      - name: deploy to AWS
        uses: ./.github/actions/deploy
        if: env.DOCS_CHANGED == 'true'
        with:
          aws_role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_s3_bucket_name: ${{ secrets.AWS_S3_BUCKET_NAME }}
          aws_cloudfront_id: ${{ secrets.AWS_CLOUDFRONT_ID }}

      - name: deploy storybook using chromatic
        uses: ./.github/actions/chromatic
        if: env.UI_CHANGED == 'true'
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: packages/ui
          storybookBuildDir: storybook-static
