name: Build & Deploy Docs
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
#   push:
#     branches:
#       - dev
#     paths:
#       - "app/docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: ./.github/actions/setup

      - name: build
        run: turbo build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync out s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
