name: ci
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ci setup
        uses: ./.github/actions/setup

        with:
          node-version: 20
